configuration: Release

skip_non_tags: true

install:
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - cmd: nuget install GitVersion.CommandLine -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre

version: 0.4.1.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore

build:
  verbosity: normal
  project: IntacctClient.sln
  parallel: true

after_build:    
  - cmd: nuget pack IntacctClient.nuspec -version "%APPVEYOR_BUILD_VERSION%" -prop "target=%CONFIGURATION%"

artifacts:
  - path: '*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: ySslogwTtqIQ0UejiNAnGezJvjZ8B6t0w2xIVYlIWH2/lZ6Ixf6dfylIod/0DGW+
  skip_symbols: true
  artifact: /.*\.nupkg/
