configuration: Release

install:
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - cmd: nuget install GitVersion.CommandLine -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre

version: 0.0.3.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore

build:
  verbosity: normal
  project: IntacctClient.sln
  parallel: true

after_build:    
  - cmd: nuget pack IntacctClient.nuspec -version "%APPVEYOR_BUILD_VERSION%" -prop "target=%CONFIGURATION%"

artifacts:
  - path: '*.nupkg'
